import type { ReactNode } from 'react';
import { Text } from '@fluentui/react-components';

/** Section header: small uppercase label with an accent underline (docs/06 section 2). */
export function SectionHeader({ children }: { children: ReactNode }): ReactNode {
  return (
    <h2 className="pb-section-header">
      <span>{children}</span>
    </h2>
  );
}

export function Card({
  children,
  tinted = false,
  testId,
}: {
  children: ReactNode;
  tinted?: boolean;
  testId?: string;
}): ReactNode {
  return (
    <section className={tinted ? 'pb-card pb-card-tinted' : 'pb-card'} data-testid={testId}>
      {children}
    </section>
  );
}

/** Stat tile: a label and a key number in the brand color. */
export function StatTile({
  label,
  value,
  hint,
}: {
  label: string;
  value: string;
  hint?: string | undefined;
}): ReactNode {
  return (
    <div className="pb-stat-tile" role="group" aria-label={label}>
      <Text size={200} className="pb-stat-label">
        {label}
      </Text>
      <Text size={700} weight="semibold" className="pb-stat-value">
        {value}
      </Text>
      {hint !== undefined ? (
        <Text size={200} className="pb-stat-hint">
          {hint}
        </Text>
      ) : null}
    </div>
  );
}

export function AiDraftBadge(): ReactNode {
  return (
    <span className="pb-ai-draft" title="Generated by an assistant and not yet approved">
      AI draft
    </span>
  );
}

export function PlaceholderPage({
  title,
  phase,
  modules,
}: {
  title: string;
  phase: string;
  modules: string;
}): ReactNode {
  return (
    <Card>
      <SectionHeader>{title}</SectionHeader>
      <p>
        This area arrives in {phase} ({modules}). See docs/09 for the roadmap and exit criteria.
      </p>
    </Card>
  );
}

export function ErrorState({
  title,
  detail,
}: {
  title: string;
  detail?: string | undefined;
}): ReactNode {
  return (
    <Card testId="error-state">
      <SectionHeader>{title}</SectionHeader>
      {detail !== undefined ? <p>{detail}</p> : null}
    </Card>
  );
}
