import { Fragment } from 'react';
import type { ReactNode } from 'react';
import { Link } from '@tanstack/react-router';
import { previewMode } from '../app/env.js';
import { MISSING } from '../lib/format.js';

/** Section header: small uppercase label with an accent underline (docs/06 section 2), optional aside on the right. */
export function SectionHeader({
  children,
  aside,
}: {
  children: ReactNode;
  aside?: ReactNode;
}): ReactNode {
  return (
    <h2 className="pb-section-header">
      <span>{children}</span>
      {aside !== undefined ? <span className="pb-section-aside">{aside}</span> : null}
    </h2>
  );
}

export function Card({
  children,
  tinted = false,
  tone,
  testId,
}: {
  children: ReactNode;
  tinted?: boolean;
  tone?: 'error' | undefined;
  testId?: string;
}): ReactNode {
  const className = [
    'pb-card',
    tinted ? 'pb-card-tinted' : '',
    tone === 'error' ? 'pb-card-error' : '',
  ]
    .filter(Boolean)
    .join(' ');
  return (
    <section className={className} data-testid={testId}>
      {children}
    </section>
  );
}

/**
 * Stat tile: a label and a key number in the brand colour, optionally with a small figure (a
 * sparkline) beside the number. Plain spans: Fluent Text would inject its own sizes at runtime.
 */
export function StatTile({
  label,
  value,
  hint,
  tone,
  figure,
}: {
  label: string;
  value: string;
  hint?: string | undefined;
  tone?: 'good' | 'watch' | 'bad' | undefined;
  figure?: ReactNode;
}): ReactNode {
  const missing = value === MISSING || value === 'NM';
  const number = (
    <span className={missing ? 'pb-stat-value is-missing' : 'pb-stat-value'}>{value}</span>
  );
  return (
    <div className="pb-stat-tile" role="group" aria-label={label} data-tone={tone}>
      <span className="pb-stat-label">{label}</span>
      {figure !== undefined && figure !== null ? (
        <span className="pb-stat-row">
          {number}
          {figure}
        </span>
      ) : (
        number
      )}
      {hint !== undefined ? <span className="pb-stat-hint">{hint}</span> : null}
    </div>
  );
}

/** A right-aligned numeric table cell; the missing placeholder and NM render muted. */
export function NumCell({ children }: { children: string }): ReactNode {
  const missing = children === MISSING || children === 'NM';
  return <td className={missing ? 'num is-missing' : 'num'}>{children}</td>;
}

export function AiDraftBadge(): ReactNode {
  return (
    <span className="pb-ai-draft" title="Generated by an assistant and not yet approved">
      AI draft
    </span>
  );
}

/** Kept for router.tsx; the phase pages are the single implementation. */
export function PlaceholderPage(props: {
  title: string;
  phase: string;
  modules: string;
}): ReactNode {
  return <PhasePage {...props} />;
}

export function ErrorState({
  title,
  detail,
}: {
  title: string;
  detail?: string | undefined;
}): ReactNode {
  return (
    <Card tone="error" testId="error-state">
      <SectionHeader>{title}</SectionHeader>
      {detail !== undefined ? <p>{detail}</p> : null}
    </Card>
  );
}

/** Page title row: a serif title (docs/06), the as-of or context line, and optional actions on the right. */
export function PageHeader({
  title,
  meta,
  actions,
  testId,
}: {
  title: ReactNode;
  meta?: ReactNode;
  actions?: ReactNode;
  testId?: string | undefined;
}): ReactNode {
  return (
    <div className="pb-banner" data-testid={testId}>
      <h1>{title}</h1>
      {meta !== undefined ? <span className="pb-meta">{meta}</span> : null}
      {actions !== undefined ? <span className="pb-banner-actions">{actions}</span> : null}
    </div>
  );
}

/** Secondary navigation inside an area (tabs). Paths are absolute so hash and browser history both work. */
export function TabNav({
  items,
  label,
}: {
  items: { to: string; label: string; exact?: boolean | undefined }[];
  label: string;
}): ReactNode {
  return (
    <nav className="pb-tabs" aria-label={label}>
      {items.map((t) => (
        <Link
          key={t.to}
          to={t.to}
          activeOptions={{ exact: t.exact ?? false }}
          activeProps={{ 'aria-current': 'page' }}
          resetScroll={false}
        >
          {t.label}
        </Link>
      ))}
    </nav>
  );
}

export type Tone = 'neutral' | 'good' | 'watch' | 'bad' | 'brand' | 'accent';

/** Status with a dot and a word, never colour alone (docs/06). plain drops the dot for category chips. */
export function Badge({
  tone = 'neutral',
  plain = false,
  children,
}: {
  tone?: Tone;
  plain?: boolean;
  children: ReactNode;
}): ReactNode {
  return (
    <span className={`pb-badge pb-badge-${tone}${plain ? ' pb-badge-plain' : ''}`}>
      <span className="pb-badge-dot" aria-hidden="true" />
      {children}
    </span>
  );
}

/** Label and value pairs in two or four columns; values keep tabular figures. */
export function KeyValueTable({
  rows,
  label,
  columns = 2,
}: {
  rows: { label: string; value: ReactNode }[];
  label: string;
  columns?: 1 | 2;
}): ReactNode {
  const pairs: { label: string; value: ReactNode }[][] = [];
  for (let i = 0; i < rows.length; i += columns) pairs.push(rows.slice(i, i + columns));
  return (
    <div className="pb-table-wrap">
      <table className="pb-table pb-kv" aria-label={label}>
        <tbody>
          {pairs.map((pair, i) => (
            <tr key={i}>
              {pair.map((r) => (
                <Fragment key={r.label}>
                  <th scope="row">{r.label}</th>
                  <td>{r.value}</td>
                </Fragment>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export function Toolbar({ children, end }: { children: ReactNode; end?: ReactNode }): ReactNode {
  return (
    <div className="pb-toolbar">
      {children}
      {end !== undefined ? <div className="pb-toolbar-end">{end}</div> : null}
    </div>
  );
}

/** Label above a control inside a Toolbar. */
export function Field({ children }: { children: ReactNode }): ReactNode {
  return <div className="pb-field">{children}</div>;
}

/** The horizon mark: the sign-in motif at 56 by 20, decorative. */
function HorizonMark(): ReactNode {
  return (
    <svg className="pb-empty-mark" viewBox="0 0 56 20" aria-hidden="true" focusable="false">
      <line x1="0" y1="6.5" x2="56" y2="6.5" stroke="currentColor" strokeWidth="1" />
      <line x1="8" y1="14.5" x2="48" y2="14.5" stroke="currentColor" strokeWidth="1" />
      <circle cx="28" cy="6.5" r="2.5" fill="currentColor" />
    </svg>
  );
}

/** Nothing to show, said plainly, with the reason and optionally what would make it appear. */
export function EmptyState({
  title,
  detail,
  testId,
}: {
  title: string;
  detail?: string | undefined;
  testId?: string | undefined;
}): ReactNode {
  return (
    <div className="pb-empty" data-testid={testId}>
      <HorizonMark />
      <p className="pb-empty-title">{title}</p>
      {detail !== undefined ? <p className="pb-empty-detail">{detail}</p> : null}
    </div>
  );
}

/** Page-level loading. aria-busy, never role="status": the banner must stay the only status element on app pages. */
export function PageSkeleton({
  tiles = 0,
  rows = 3,
}: {
  tiles?: number;
  rows?: number;
}): ReactNode {
  return (
    <div className="pb-skeleton" aria-busy="true">
      <span className="pb-visually-hidden">Loading</span>
      <div className="pb-skeleton-bar is-title" />
      {tiles > 0 ? (
        <div className="pb-skeleton-tiles">
          {Array.from({ length: tiles }, (_, i) => (
            <div key={i} className="pb-skeleton-tile" />
          ))}
        </div>
      ) : null}
      {Array.from({ length: rows }, (_, i) => (
        <div key={i} className="pb-skeleton-bar" />
      ))}
    </div>
  );
}

/** Marks an action the static preview only simulates (docs/16: no server, nothing saved, nothing audited). */
export function SimulatedBadge(): ReactNode {
  if (!previewMode) return null;
  return (
    <span
      className="pb-simulated"
      title="Simulated in this preview: not saved, not audited, resets when the page reloads"
    >
      Simulated
    </span>
  );
}

/** A page that will arrive in a later phase: says which, and what the data would show. */
export function PhasePage({
  title,
  phase,
  modules,
  children,
}: {
  title: string;
  phase: string;
  modules: string;
  children?: ReactNode;
}): ReactNode {
  return (
    <>
      <PageHeader title={title} meta={`${phase}: ${modules}`} />
      <Card>
        <EmptyState
          title={`${title} arrives in ${phase}`}
          detail="The data model and workflow for this area are specified (docs/04, docs/18); the screens are built once the earlier phases pass their exit criteria."
        />
        {children}
      </Card>
    </>
  );
}
