import type { z } from 'zod';
import * as s from './schemas.js';

export type HttpMethod = 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE';

export interface RouteDefinition {
  method: HttpMethod;
  path: string;
  summary: string;
  tags: string[];
  /** Roles that may call the route; empty means any authenticated user. */
  roles: readonly string[];
  auth: boolean;
  query?: z.ZodTypeAny;
  body?: z.ZodTypeAny;
  response: z.ZodTypeAny;
  responseStatus?: number;
}

export const API_PREFIX = '/api/v1';

/** The single route table the API implements and the OpenAPI document is generated from. */
export const ROUTES: readonly RouteDefinition[] = [
  {
    method: 'GET',
    path: '/health/live',
    summary: 'Liveness',
    tags: ['health'],
    roles: [],
    auth: false,
    response: s.healthLive,
  },
  {
    method: 'GET',
    path: '/health/ready',
    summary: 'Readiness: database and adapters',
    tags: ['health'],
    roles: [],
    auth: false,
    response: s.healthReady,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/auth/me`,
    summary: 'The calling principal',
    tags: ['auth'],
    roles: [],
    auth: true,
    response: s.principal,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/auth/mock-users`,
    summary: 'Mock sign-in choices (prototype only, never in production)',
    tags: ['auth'],
    roles: [],
    auth: false,
    response: s.mockUserList,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/flags`,
    summary: 'Feature flags and kill switches',
    tags: ['ops'],
    roles: [],
    auth: true,
    response: s.featureFlagList,
  },
  {
    method: 'PATCH',
    path: `${API_PREFIX}/flags/{key}`,
    summary: 'Set a flag (audited)',
    tags: ['ops'],
    roles: ['platform_admin'],
    auth: true,
    body: s.featureFlagPatch,
    response: s.featureFlag,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/investments`,
    summary: 'Portfolio grid with calculated metrics',
    tags: ['portfolio'],
    roles: [],
    auth: true,
    query: s.investmentListQuery,
    response: s.investmentPage,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/investments/{id}`,
    summary: 'Investment detail (404 when not visible)',
    tags: ['portfolio'],
    roles: [],
    auth: true,
    response: s.investmentDetail,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/sponsors`,
    summary: 'Sponsors',
    tags: ['portfolio'],
    roles: [],
    auth: true,
    query: s.pageQuery,
    response: s.sponsorPage,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/vehicles`,
    summary: 'Firm vehicles',
    tags: ['portfolio'],
    roles: [],
    auth: true,
    response: s.vehicleList,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/data-health`,
    summary: 'Data Health page (M1)',
    tags: ['data'],
    roles: [],
    auth: true,
    response: s.dataHealth,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/data-dictionary`,
    summary: 'Data Dictionary from config/definitions.json (M1)',
    tags: ['data'],
    roles: [],
    auth: true,
    response: s.dataDictionary,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/investments/{id}/performance`,
    summary: 'Quarterly operating and credit series for the Performance tab (404 when not visible)',
    tags: ['portfolio'],
    roles: [],
    auth: true,
    query: s.asOfQuery,
    response: s.investmentPerformance,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/vehicles/{id}`,
    summary: 'Vehicle detail: positions, pooled metrics, fund and LP commitments',
    tags: ['portfolio'],
    roles: [],
    auth: true,
    query: s.asOfQuery,
    response: s.vehicleDetail,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/sponsors/{id}`,
    summary: 'Sponsor 360: funds, aliases, our positions and commitments',
    tags: ['portfolio'],
    roles: [],
    auth: true,
    query: s.asOfQuery,
    response: s.sponsorDetail,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/commitments`,
    summary:
      'Fund commitments with called, distributed and unfunded (primary program and separate accounts)',
    tags: ['portfolio'],
    roles: [],
    auth: true,
    query: s.asOfQuery,
    response: s.commitmentList,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/clients`,
    summary:
      'Client look-through: commitments and share of vehicle positions (entitled clients only)',
    tags: ['clients'],
    roles: [],
    auth: true,
    query: s.asOfQuery,
    response: s.clientList,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/valuations`,
    summary: 'Valuation versions and states across the portfolio (M10 board)',
    tags: ['valuations'],
    roles: [],
    auth: true,
    query: s.valuationListQuery,
    response: s.valuationPage,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/capital-notices`,
    summary: 'Capital notices with settlement status and the attention list (M16)',
    tags: ['capital'],
    roles: [],
    auth: true,
    query: s.capitalNoticeListQuery,
    response: s.capitalNoticePage,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/capital-notices/{id}`,
    summary:
      'Capital notice detail with linked cash flows (404 when not visible; never bank details)',
    tags: ['capital'],
    roles: [],
    auth: true,
    query: s.asOfQuery,
    response: s.capitalNoticeDetail,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/analytics/summary`,
    summary: 'Portfolio analytics: pooled metrics, exposures, NAV and cash-flow series (M12, M13)',
    tags: ['analytics'],
    roles: [],
    auth: true,
    query: s.asOfQuery,
    response: s.analyticsSummary,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/monitoring/watchlist`,
    summary: 'Positions with monitoring flags from config thresholds (M9)',
    tags: ['analytics'],
    roles: [],
    auth: true,
    query: s.asOfQuery,
    response: s.watchlist,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/reports/weekly`,
    summary: 'Weekly portfolio report assembled from the figures (M12)',
    tags: ['reporting'],
    roles: [],
    auth: true,
    query: s.asOfQuery,
    response: s.weeklyReport,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/audit/events`,
    summary: 'Audit trail: who did what, when (SEC-11.1); never business values',
    tags: ['admin'],
    roles: ['operations', 'approver', 'auditor', 'platform_admin'],
    auth: true,
    query: s.auditQuery,
    response: s.auditPage,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/taxonomy`,
    summary: 'Taxonomy domains and terms (docs/03)',
    tags: ['data'],
    roles: [],
    auth: true,
    response: s.taxonomy,
  },
  {
    method: 'GET',
    path: `${API_PREFIX}/walls`,
    summary: 'Information walls visible to the caller (SEC-5.3)',
    tags: ['admin'],
    roles: [],
    auth: true,
    response: s.wallList,
  },
];
