import type {
  AnalyticsSummary,
  CapitalNoticePage,
  CapitalNoticeRow,
  WallList,
  Watchlist,
  WatchlistItem,
  WeeklyReport,
} from '@pb/contracts';
import { ZERO, toDecimalString, valueChange } from '@pb/calc';
import type { Decimal } from '@pb/calc';
import {
  formatDate,
  formatMoic,
  formatMoneyM,
  formatPct,
  irrDisplay,
  joinList,
  labelOf,
  plural,
} from './format.js';

/**
 * Ask Portfolio Beach, mock edition (docs/07 agent inventory; config/definitions.json agentModels.default
 * is "mock"). Every answer is assembled by a template from figures the current user's own queries
 * returned, so a record the user cannot see never reaches an answer (SEC-8.5). No model is called.
 * House style (docs/07 section 2): plain statements, numbers through the formatters, the period stated,
 * no adjectives, no predictions, no em dashes.
 */

export type QuestionId =
  'attention' | 'nav' | 'capital' | 'stale' | 'sector' | 'realized' | 'largest' | 'walls';

export interface FixedQuestion {
  id: QuestionId;
  text: string;
  /** Extra stems that map a typed question onto this one; the question's own words count as well. */
  keywords: readonly string[];
}

export const QUESTIONS: readonly FixedQuestion[] = [
  {
    id: 'attention',
    text: 'Which positions need attention?',
    keywords: ['watchlist', 'watch', 'flag', 'flagged', 'risk', 'problem', 'breach', 'covenant'],
  },
  {
    id: 'nav',
    text: 'What is the portfolio NAV and how did it move?',
    keywords: [
      'value',
      'moved',
      'movement',
      'change',
      'changed',
      'quarter',
      'trend',
      'grew',
      'fell',
    ],
  },
  {
    id: 'capital',
    text: 'What capital activity is due?',
    keywords: [
      'call',
      'notice',
      'distribution',
      'funding',
      'wire',
      'cash',
      'pay',
      'overdue',
      'owe',
    ],
  },
  {
    id: 'stale',
    text: 'Which valuations are stale?',
    keywords: ['old', 'mark', 'locked', 'footnote', 'outdated', 'missing', 'unlocked'],
  },
  {
    id: 'sector',
    text: 'What is our exposure by sector?',
    keywords: ['industry', 'concentration', 'geography', 'mix', 'allocation', 'diversification'],
  },
  {
    id: 'realized',
    text: 'Which positions are realized and at what multiple?',
    keywords: ['realised', 'exit', 'exited', 'moic', 'dpi', 'sold', 'return', 'track'],
  },
  {
    id: 'largest',
    text: 'What are the largest positions?',
    keywords: ['biggest', 'top', 'holding', 'size', 'big', 'concentration', 'major'],
  },
  {
    id: 'walls',
    text: 'Who can see the walled deal?',
    keywords: [
      'wall',
      'access',
      'member',
      'restricted',
      'permission',
      'barrier',
      'visible',
      'hidden',
    ],
  },
];

export const MOCK_ASSISTANT_LINE =
  'Mock assistant: this answer is assembled from the recorded figures by a template, not generated by a model (config/definitions.json agentModels.default = mock).';

/* ---- Matching a typed question onto a fixed one ---- */

const STOPWORDS = new Set([
  'the',
  'a',
  'an',
  'is',
  'are',
  'was',
  'were',
  'be',
  'been',
  'what',
  'which',
  'how',
  'did',
  'do',
  'does',
  'our',
  'we',
  'us',
  'it',
  'its',
  'to',
  'of',
  'in',
  'on',
  'by',
  'for',
  'and',
  'or',
  'at',
  'this',
  'that',
  'these',
  'those',
  'with',
  'from',
  'as',
  'any',
  'there',
  'their',
  'they',
  'them',
  'has',
  'have',
  'had',
  'will',
  'would',
  'should',
  'could',
  'can',
  'you',
  'me',
  'my',
  'your',
  'please',
  'show',
  'tell',
  'list',
  'give',
  'about',
  'much',
  'many',
  'all',
  'some',
  'right',
  'now',
  'currently',
  'current',
  'portfolio',
  'beach',
]);

/** Lower-case word stems without stop words: "Which positions need attention?" -> ["position", "need", "attention"]. */
export function tokenize(text: string): string[] {
  const out: string[] = [];
  for (const raw of text.toLowerCase().split(/[^a-z0-9]+/)) {
    if (raw.length < 2 || STOPWORDS.has(raw)) continue;
    const stem =
      raw.length > 3 && raw.endsWith('s') && !raw.endsWith('ss') ? raw.slice(0, -1) : raw;
    if (!out.includes(stem)) out.push(stem);
  }
  return out;
}

const keywordSets = new Map<QuestionId, Set<string>>(
  QUESTIONS.map((q) => [
    q.id,
    new Set([...tokenize(q.text), ...q.keywords.flatMap((k) => tokenize(k))]),
  ]),
);

export interface QuestionMatch {
  question: FixedQuestion;
  /** Number of typed word stems the fixed question shares. */
  score: number;
}

/** The fixed question sharing the most word stems with the typed text; ties keep the earlier question; null when none overlap. */
export function matchQuestion(text: string): QuestionMatch | null {
  const tokens = tokenize(text);
  let best: QuestionMatch | null = null;
  for (const question of QUESTIONS) {
    const set = keywordSets.get(question.id);
    const score = set === undefined ? 0 : tokens.filter((t) => set.has(t)).length;
    if (score > 0 && (best === null || score > best.score)) best = { question, score };
  }
  return best;
}

/* ---- Answers ---- */

export interface AssistantInputs {
  analytics: AnalyticsSummary | null;
  watchlist: Watchlist | null;
  capitalNotices: CapitalNoticePage | null;
  weeklyReport: WeeklyReport | null;
  walls: WallList | null;
}

export interface AssistantSource {
  label: string;
  to: string;
}

export interface AssistantAnswer {
  question: FixedQuestion;
  paragraphs: string[];
  sources: AssistantSource[];
  /** False when a figure the answer needed was not available; the first paragraph says which. */
  complete: boolean;
}

type Built = Omit<AssistantAnswer, 'question'>;

const LIMIT = 5;

const SOURCES = {
  watchlist: { label: 'Watchlist', to: '/portfolio/watchlist' },
  portfolio: { label: 'Portfolio', to: '/portfolio' },
  analytics: { label: 'Analytics, Exposure', to: '/analytics' },
  performance: { label: 'Analytics, Performance', to: '/analytics/performance' },
  realizations: { label: 'Analytics, Realizations', to: '/analytics/realizations' },
  weekly: { label: 'Weekly report', to: '/reporting' },
  capital: { label: 'Capital Activity', to: '/capital-activity' },
  valuations: { label: 'Valuations', to: '/valuations' },
  access: { label: 'Admin, Access and walls', to: '/admin/access' },
} as const satisfies Record<string, AssistantSource>;

/** Sum of decimal strings as a decimal string, in exact decimals; null when no input has a value (never an invented zero). */
function sumOf(values: (string | null)[]): string | null {
  let total: Decimal | null = null;
  for (const v of values) if (v !== null) total = (total ?? ZERO).plus(v);
  return toDecimalString(total);
}

function missing(what: string, sources: AssistantSource[]): Built {
  return {
    paragraphs: [
      `${what} is not available right now, so this question cannot be answered from the recorded figures.`,
    ],
    sources,
    complete: false,
  };
}

const severity = (item: WatchlistItem): number =>
  item.flags.some((f) => f.severity === 'bad') ? 2 : item.flags.length > 0 ? 1 : 0;

function attention(watchlist: Watchlist | null): Built {
  const sources = [SOURCES.watchlist, SOURCES.portfolio];
  if (watchlist === null) return missing('The watchlist', sources);
  const { bad, watch, clear } = watchlist.counts;
  const asOf = formatDate(watchlist.asOf);
  if (watchlist.items.length === 0) {
    return {
      paragraphs: [`No position you can see carries a monitoring flag as of ${asOf}.`],
      sources,
      complete: true,
    };
  }
  const head = `As of ${asOf}, ${plural(bad, 'position')} ${bad === 1 ? 'carries' : 'carry'} a bad flag, ${watch} a watch flag and ${clear} ${clear === 1 ? 'has' : 'have'} none.`;
  const ranked = [...watchlist.items].sort(
    (a, b) => severity(b) - severity(a) || a.investmentNumber.localeCompare(b.investmentNumber),
  );
  const lines = ranked
    .slice(0, LIMIT)
    .map(
      (i) =>
        `${i.investmentNumber} ${i.companyName} (${i.vehicleName}): ${i.flags.map((f) => f.message).join('; ')}.`,
    );
  const rest = ranked.length - LIMIT;
  const tail =
    rest > 0
      ? [
          `${plural(rest, 'more position')} ${rest === 1 ? 'carries' : 'carry'} flags; the Watchlist lists every one.`,
        ]
      : [];
  return { paragraphs: [head, ...lines, ...tail], sources, complete: true };
}

function nav(analytics: AnalyticsSummary | null, report: WeeklyReport | null): Built {
  const sources = [SOURCES.performance, SOURCES.weekly];
  if (analytics === null) return missing('The analytics summary', sources);
  const a = analytics.active;
  const paragraphs = [
    `Portfolio NAV is ${formatMoneyM(a.nav)} across ${plural(analytics.activeInvestments, 'active position')} as of ${formatDate(analytics.asOf)}; invested capital is ${formatMoneyM(a.invested)}, distributions to date are ${formatMoneyM(a.distributions)} and the gross MOIC is ${formatMoic(a.grossMoic)}.`,
  ];
  // The last two quarter ends of the one NAV series: each counts every position held then, at its
  // latest Locked mark, so the two cover like with like; a point that is not calculable is said so.
  const [prev, last] = analytics.navSeries.slice(-2);
  if (last === undefined || prev === undefined) {
    paragraphs.push(
      'Fewer than two quarter-end NAV points are on record, so the quarter-over-quarter move is not calculable.',
    );
  } else if (last.value === null || prev.value === null) {
    const gap = last.value === null ? last : prev;
    paragraphs.push(
      `The quarter-over-quarter NAV move is not calculable: a position held at ${formatDate(gap.periodEnd)} has no Locked valuation for it yet.`,
    );
  } else {
    // The one mark-to-mark change rule (docs/08 section 2), in exact decimals.
    const change = toDecimalString(valueChange(last.value, prev.value));
    paragraphs.push(
      `NAV was ${formatMoneyM(prev.value)} at ${formatDate(prev.periodEnd)} and ${formatMoneyM(last.value)} at ${formatDate(last.periodEnd)}, a change of ${formatPct(change)}.`,
    );
  }
  if (report !== null && report.movers.length > 0) {
    // The report lists movers gainers first; the largest moves are the largest either way.
    const bySize = [...report.movers].sort(
      (a, b) =>
        Math.abs(Number(b.changePct)) - Math.abs(Number(a.changePct)) ||
        (a.investmentNumber < b.investmentNumber ? -1 : 1),
    );
    paragraphs.push(
      `The largest Locked fair value moves against the prior quarter are ${joinList(
        bySize.slice(0, 3).map((m) => `${m.companyName} (${formatPct(m.changePct)})`),
      )}.`,
    );
  }
  return { paragraphs, sources, complete: true };
}

function capital(notices: CapitalNoticePage | null, report: WeeklyReport | null): Built {
  const sources = [SOURCES.capital, SOURCES.weekly];
  const picked =
    notices !== null
      ? { rows: notices.attention, asOf: notices.asOf, from: 'the capital notices' }
      : report !== null
        ? {
            rows: report.capitalActivity,
            asOf: report.asOf,
            from: "the weekly report's capital activity section",
          }
        : null;
  if (picked === null) return missing('Capital notice data', sources);
  const asOf = formatDate(picked.asOf);
  if (picked.rows.length === 0) {
    return {
      paragraphs: [`No capital notice needs attention as of ${asOf} (from ${picked.from}).`],
      sources,
      complete: true,
    };
  }
  const rows = [...picked.rows].sort(
    (a, b) => a.dueDate.localeCompare(b.dueDate) || a.id.localeCompare(b.id),
  );
  const describe = (n: CapitalNoticeRow): string => {
    const target = n.companyName ?? n.sponsorFundName ?? n.vehicleName;
    const overdue = n.daysToDue < 0 ? ` (overdue by ${plural(-n.daysToDue, 'day')})` : '';
    return `${labelOf(n.noticeType)} of ${formatMoneyM(n.amount)} for ${target}, due ${formatDate(n.dueDate)}${overdue}.`;
  };
  const head = `${plural(rows.length, 'capital notice')} ${rows.length === 1 ? 'needs' : 'need'} attention as of ${asOf}: not yet reconciled, or due within the alert window (from ${picked.from}).`;
  const lines = rows.slice(0, LIMIT).map(describe);
  const rest = rows.length - LIMIT;
  const tail: string[] = [];
  // No total: calls are paid out and distributions, interest and repayments come in, so one sum of
  // the two directions would mean nothing.
  if (rest > 0) tail.push(`${rest} more are listed under Capital Activity.`);
  return { paragraphs: [head, ...lines, ...tail], sources, complete: true };
}

function stale(report: WeeklyReport | null): Built {
  const sources = [SOURCES.weekly, SOURCES.valuations];
  if (report === null) return missing('The weekly report', sources);
  const period = formatDate(report.periodEnd);
  const asOf = formatDate(report.asOf);
  const items = report.staleValuations;
  if (items.length === 0) {
    return {
      paragraphs: [`Every active position has a Locked valuation for ${period} as of ${asOf}.`],
      sources,
      complete: true,
    };
  }
  const head = `${plural(items.length, 'active position')} ${items.length === 1 ? 'has' : 'have'} no Locked valuation for ${period} as of ${asOf}.`;
  const lines = items
    .slice(0, LIMIT)
    .map((s) => `${s.investmentNumber} ${s.companyName}: ${s.footnote}`);
  const rest = items.length - LIMIT;
  const tail = rest > 0 ? [`${rest} more are listed in the weekly report.`] : [];
  return { paragraphs: [head, ...lines, ...tail], sources, complete: true };
}

function sector(analytics: AnalyticsSummary | null): Built {
  const sources = [SOURCES.analytics];
  if (analytics === null) return missing('The analytics summary', sources);
  const buckets = [...analytics.exposures.sector].sort(
    (a, b) => Number(b.navShare ?? '0') - Number(a.navShare ?? '0'),
  );
  if (buckets.length === 0) {
    return {
      paragraphs: ['No sector exposure is on record for the positions you can see.'],
      sources,
      complete: true,
    };
  }
  const top = buckets.slice(0, LIMIT);
  return {
    paragraphs: [
      `By NAV as of ${formatDate(analytics.asOf)}, the largest sectors are ${joinList(
        top.map(
          (b) =>
            `${b.label} at ${formatPct(b.navShare)} (${formatMoneyM(b.nav)}, ${plural(b.count, 'position')})`,
        ),
      )}.`,
      `${plural(buckets.length, 'sector')} in total; each share is the sector's NAV over the NAV of every position you can see.`,
    ],
    sources,
    complete: true,
  };
}

function realized(analytics: AnalyticsSummary | null): Built {
  const sources = [SOURCES.realizations, SOURCES.portfolio];
  if (analytics === null) return missing('The analytics summary', sources);
  const n = analytics.realizedInvestments;
  if (n === 0) {
    return {
      paragraphs: ['No position you can see is realized.'],
      sources,
      complete: true,
    };
  }
  const m = analytics.realized;
  return {
    paragraphs: [
      `${plural(n, 'position')} ${n === 1 ? 'is' : 'are'} realized as of ${formatDate(analytics.asOf)}. Pooled across them, invested capital is ${formatMoneyM(m.invested)}, distributions are ${formatMoneyM(m.distributions)}, the gross MOIC is ${formatMoic(m.grossMoic)}, DPI is ${formatMoic(m.dpi)} and the gross IRR is ${irrDisplay(m)}.`,
      'Each realized position with its own multiple is on the Portfolio page with Active only switched off.',
    ],
    sources,
    complete: true,
  };
}

function largest(analytics: AnalyticsSummary | null): Built {
  const sources = [SOURCES.analytics, SOURCES.portfolio];
  if (analytics === null) return missing('The analytics summary', sources);
  const top = analytics.topPositions.slice(0, LIMIT);
  if (top.length === 0) {
    return {
      paragraphs: ['No position with a Locked NAV is on record among the positions you can see.'],
      sources,
      complete: true,
    };
  }
  const lines = top.map(
    (p, i) =>
      `${i + 1}. ${p.companyName} (${p.vehicleName}): ${formatMoneyM(p.nav)}, ${formatPct(p.navShare)} of NAV, gross MOIC ${formatMoic(p.grossMoic)}.`,
  );
  const shares = top.map((p) => p.navShare);
  const tail = shares.includes(null)
    ? []
    : [`Together they hold ${formatPct(sumOf(shares))} of NAV.`];
  return {
    paragraphs: [
      `The ${top.length} largest positions by NAV as of ${formatDate(analytics.asOf)}:`,
      ...lines,
      ...tail,
    ],
    sources,
    complete: true,
  };
}

function walls(list: WallList | null): Built {
  const sources = [SOURCES.access];
  if (list === null) return missing('Wall data', sources);
  const rule =
    "A walled record is visible only to the wall's named members. Approvers and platform admins manage walls but see a walled record only when they are members; for everyone else it does not appear in any list, search or answer (SEC-5.3, SEC-8.5).";
  if (list.walls.length === 0) {
    return { paragraphs: ['No wall is visible to you.', rule], sources, complete: true };
  }
  const lines = list.walls.map(
    (w) =>
      `${w.name}: ${plural(w.members.length, 'member')} visible to you (${joinList(w.members.map((m) => m.displayName))}), covering ${plural(w.records.length, 'record')}: ${joinList(
        w.records.map((r) => r.label ?? 'a record you cannot see'),
      )}.`,
  );
  return { paragraphs: [...lines, rule], sources, complete: true };
}

/** Builds the answer for a fixed question from the figures the caller's queries returned. */
export function answerQuestion(id: QuestionId, inputs: AssistantInputs): AssistantAnswer {
  const question = QUESTIONS.find((q) => q.id === id) ?? QUESTIONS[0]!;
  const built = ((): Built => {
    switch (id) {
      case 'attention':
        return attention(inputs.watchlist);
      case 'nav':
        return nav(inputs.analytics, inputs.weeklyReport);
      case 'capital':
        return capital(inputs.capitalNotices, inputs.weeklyReport);
      case 'stale':
        return stale(inputs.weeklyReport);
      case 'sector':
        return sector(inputs.analytics);
      case 'realized':
        return realized(inputs.analytics);
      case 'largest':
        return largest(inputs.analytics);
      case 'walls':
        return walls(inputs.walls);
    }
  })();
  return { question, ...built };
}
